#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EnergyProduction */

#ifndef _Included_EnergyProduction
#define _Included_EnergyProduction
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     EnergyProduction
	* Method:    energyProduction
	* Signature: ()F
	*/
	JNIEXPORT jfloat JNICALL Java_EnergyProduction_energyProduction
	(JNIEnv *, jclass);

	/*
	* Class:     EnergyProduction
	* Method:    turnOn
	* Signature: (I)I
	*/
	JNIEXPORT jint JNICALL Java_EnergyProduction_turnOn
	(JNIEnv *, jclass, jint);

	/*
	* Class:     EnergyProduction
	* Method:    isOn
	* Signature: ()I
	*/
	JNIEXPORT jint JNICALL Java_EnergyProduction_isOn
	(JNIEnv *, jclass);

	/*
	* Class:     EnergyProduction
	* Method:    error
	* Signature: ()Ljava/lang/String;
	*/
	JNIEXPORT jstring JNICALL Java_EnergyProduction_error
	(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
