/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Trab1_Class */

#ifndef _Included_Trab1_Class
#define _Included_Trab1_Class
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Trab1_Class
 * Method:    energyProduction
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_Trab1_1Class_energyProduction
  (JNIEnv *, jclass);

/*
 * Class:     Trab1_Class
 * Method:    turnOn
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Trab1_1Class_turnOn
  (JNIEnv *, jclass, jint, int state);

/*
 * Class:     Trab1_Class
 * Method:    isOn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Trab1_1Class_isOn
  (JNIEnv *, jclass);

/*
 * Class:     Trab1_Class
 * Method:    error
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Trab1_1Class_error
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
